In [1]:
import pandas as pd

In [3]:
df=pd.read_csv("D:\DS\cardata.csv")

In [4]:
print(df)

    manufacturer   model  displ  year  cyl       trans drv  cty  hwy fl  \
0           audi      a4    1.8  1999    4    auto(l5)   f   18   29  p
1           audi      a4    1.8  1999    4  manual(m5)   f   21   29  p
2           audi      a4    2.0  2008    4  manual(m6)   f   20   31  p
3           audi      a4    2.0  2008    4    auto(av)   f   21   30  p
4           audi      a4    2.8  1999    6    auto(l5)   f   16   26  p
..           ...     ...    ...   ...  ...         ...  ..  ...  ... ..
229   volkswagen  passat    2.0  2008    4    auto(s6)   f   19   28  p
230   volkswagen  passat    2.0  2008    4  manual(m6)   f   21   29  p
231   volkswagen  passat    2.8  1999    6    auto(l5)   f   16   26  p
232   volkswagen  passat    2.8  1999    6  manual(m5)   f   18   26  p
233   volkswagen  passat    3.6  2008    6    auto(s6)   f   17   26  p

       class
0    compact
1    compact
2    compact
3    compact
4    compact
..       ...
229  midsize
230  midsize
231  midsize
232  midsize
233  midsize

[234 rows x 11 columns]

In [5]:
col=["model"]
df.drop(columns=col, axis=1)

    manufacturer  displ  year  cyl       trans drv  cty  hwy fl    class
0           audi    1.8  1999    4    auto(l5)   f   18   29  p  compact
1           audi    1.8  1999    4  manual(m5)   f   21   29  p  compact
2           audi    2.0  2008    4  manual(m6)   f   20   31  p  compact
3           audi    2.0  2008    4    auto(av)   f   21   30  p  compact
4           audi    2.8  1999    6    auto(l5)   f   16   26  p  compact
..           ...    ...   ...  ...         ...  ..  ...  ... ..      ...
229   volkswagen    2.0  2008    4    auto(s6)   f   19   28  p  midsize
230   volkswagen    2.0  2008    4  manual(m6)   f   21   29  p  midsize
231   volkswagen    2.8  1999    6    auto(l5)   f   16   26  p  midsize
232   volkswagen    2.8  1999    6  manual(m5)   f   18   26  p  midsize
233   volkswagen    3.6  2008    6    auto(s6)   f   17   26  p  midsize

[234 rows x 10 columns]

In [6]:
cols=["hwy","class"]
df.drop(columns=cols, axis=1)

    manufacturer   model  displ  year  cyl       trans drv  cty fl
0           audi      a4    1.8  1999    4    auto(l5)   f   18  p
1           audi      a4    1.8  1999    4  manual(m5)   f   21  p
2           audi      a4    2.0  2008    4  manual(m6)   f   20  p
3           audi      a4    2.0  2008    4    auto(av)   f   21  p
4           audi      a4    2.8  1999    6    auto(l5)   f   16  p
..           ...     ...    ...   ...  ...         ...  ..  ... ..
229   volkswagen  passat    2.0  2008    4    auto(s6)   f   19  p
230   volkswagen  passat    2.0  2008    4  manual(m6)   f   21  p
231   volkswagen  passat    2.8  1999    6    auto(l5)   f   16  p
232   volkswagen  passat    2.8  1999    6  manual(m5)   f   18  p
233   volkswagen  passat    3.6  2008    6    auto(s6)   f   17  p

[234 rows x 9 columns]

In [7]:
new_column_names = {'model': 'car_model', 'trans': 'ts'}
df = df.rename(columns=new_column_names)

In [8]:
print(df)

    manufacturer car_model  displ  year  cyl          ts drv  cty  hwy fl  \
0           audi        a4    1.8  1999    4    auto(l5)   f   18   29  p
1           audi        a4    1.8  1999    4  manual(m5)   f   21   29  p
2           audi        a4    2.0  2008    4  manual(m6)   f   20   31  p
3           audi        a4    2.0  2008    4    auto(av)   f   21   30  p
4           audi        a4    2.8  1999    6    auto(l5)   f   16   26  p
..           ...       ...    ...   ...  ...         ...  ..  ...  ... ..
229   volkswagen    passat    2.0  2008    4    auto(s6)   f   19   28  p
230   volkswagen    passat    2.0  2008    4  manual(m6)   f   21   29  p
231   volkswagen    passat    2.8  1999    6    auto(l5)   f   16   26  p
232   volkswagen    passat    2.8  1999    6  manual(m5)   f   18   26  p
233   volkswagen    passat    3.6  2008    6    auto(s6)   f   17   26  p

       class
0    compact
1    compact
2    compact
3    compact
4    compact
..       ...
229  midsize
230  midsize
231  midsize
232  midsize
233  midsize

[234 rows x 11 columns]

In [9]:
empty_rows = df.isnull().all(axis=1)


print(empty_rows)

num_empty_rows = empty_rows.sum()
print("Number of empty rows:", num_empty_rows)

0      False
1      False
2      False
3      False
4      False
       ...
229    False
230    False
231    False
232    False
233    False
Length: 234, dtype: bool
Number of empty rows: 0

In [10]:

missing_values_in_row = df.isnull().any(axis=1)


print(df[missing_values_in_row])

num_missing_values_in_row = missing_values_in_row.sum()
print("Number of rows with missing values:", num_missing_values_in_row)

Empty DataFrame
Columns: [manufacturer, car_model, displ, year, cyl, ts, drv, cty, hwy, fl, class]
Index: []
Number of rows with missing values: 0

In [11]:

df_cleaned = df.dropna()
print(df_cleaned)

    manufacturer car_model  displ  year  cyl          ts drv  cty  hwy fl  \
0           audi        a4    1.8  1999    4    auto(l5)   f   18   29  p
1           audi        a4    1.8  1999    4  manual(m5)   f   21   29  p
2           audi        a4    2.0  2008    4  manual(m6)   f   20   31  p
3           audi        a4    2.0  2008    4    auto(av)   f   21   30  p
4           audi        a4    2.8  1999    6    auto(l5)   f   16   26  p
..           ...       ...    ...   ...  ...         ...  ..  ...  ... ..
229   volkswagen    passat    2.0  2008    4    auto(s6)   f   19   28  p
230   volkswagen    passat    2.0  2008    4  manual(m6)   f   21   29  p
231   volkswagen    passat    2.8  1999    6    auto(l5)   f   16   26  p
232   volkswagen    passat    2.8  1999    6  manual(m5)   f   18   26  p
233   volkswagen    passat    3.6  2008    6    auto(s6)   f   17   26  p

       class
0    compact
1    compact
2    compact
3    compact
4    compact
..       ...
229  midsize
230  midsize
231  midsize
232  midsize
233  midsize

[234 rows x 11 columns]

In [12]:
df2=pd.read_csv("d:\\ds\\biostats.csv")

In [13]:
print(df2)

    Name Sex  Age  Height  Weigth
0   Alex   M   41      74     170
1   Bert   M   42      68     166
2   Carl   M   32      70     155
3   Dave   M   39      72     167
4   Elly   F   30      66     124
5   Fran   F   33      66     115
6   Gwen   F   26      64     121
7   Hank   M   30      71     158
8   Ivan   M   53      72     175
9   Jake   M   32      69     143
10  Kate   F   47      69     139
11  Luke   M   34      72     163
12  Myra   F   23      62      98
13  Neil   M   36      75     160
14  Omar   M   38      70     145
15  Page   F   31      67     135
16  Quin   M   29      71     176
17  Ruth   F   28      65     131

In [14]:
sorted_df = df2.sort_values(by='Name')
print(sorted_df)

    Name Sex  Age  Height  Weigth
0   Alex   M   41      74     170
1   Bert   M   42      68     166
2   Carl   M   32      70     155
3   Dave   M   39      72     167
4   Elly   F   30      66     124
5   Fran   F   33      66     115
6   Gwen   F   26      64     121
7   Hank   M   30      71     158
8   Ivan   M   53      72     175
9   Jake   M   32      69     143
10  Kate   F   47      69     139
11  Luke   M   34      72     163
12  Myra   F   23      62      98
13  Neil   M   36      75     160
14  Omar   M   38      70     145
15  Page   F   31      67     135
16  Quin   M   29      71     176
17  Ruth   F   28      65     131

In [15]:
sorted_df = df2.sort_values(by='Name',ascending=False)
print(sorted_df)

    Name Sex  Age  Height  Weigth
17  Ruth   F   28      65     131
16  Quin   M   29      71     176
15  Page   F   31      67     135
14  Omar   M   38      70     145
13  Neil   M   36      75     160
12  Myra   F   23      62      98
11  Luke   M   34      72     163
10  Kate   F   47      69     139
9   Jake   M   32      69     143
8   Ivan   M   53      72     175
7   Hank   M   30      71     158
6   Gwen   F   26      64     121
5   Fran   F   33      66     115
4   Elly   F   30      66     124
3   Dave   M   39      72     167
2   Carl   M   32      70     155
1   Bert   M   42      68     166
0   Alex   M   41      74     170

In [17]:
sorted_df = df2.sort_values(by=['Sex', 'Age'])
print(sorted_df)

    Name Sex  Age  Height  Weigth
12  Myra   F   23      62      98
6   Gwen   F   26      64     121
17  Ruth   F   28      65     131
4   Elly   F   30      66     124
15  Page   F   31      67     135
5   Fran   F   33      66     115
10  Kate   F   47      69     139
16  Quin   M   29      71     176
7   Hank   M   30      71     158
2   Carl   M   32      70     155
9   Jake   M   32      69     143
11  Luke   M   34      72     163
13  Neil   M   36      75     160
14  Omar   M   38      70     145
3   Dave   M   39      72     167
0   Alex   M   41      74     170
1   Bert   M   42      68     166
8   Ivan   M   53      72     175

In [18]:
filtered_df = df2[df2['Height'] > 30]
print(filtered_df)

    Name Sex  Age  Height  Weigth
0   Alex   M   41      74     170
1   Bert   M   42      68     166
2   Carl   M   32      70     155
3   Dave   M   39      72     167
4   Elly   F   30      66     124
5   Fran   F   33      66     115
6   Gwen   F   26      64     121
7   Hank   M   30      71     158
8   Ivan   M   53      72     175
9   Jake   M   32      69     143
10  Kate   F   47      69     139
11  Luke   M   34      72     163
12  Myra   F   23      62      98
13  Neil   M   36      75     160
14  Omar   M   38      70     145
15  Page   F   31      67     135
16  Quin   M   29      71     176
17  Ruth   F   28      65     131

In [19]:
filtered_df = df2[(df2['Age'] > 10) & (df2['Height'] < 70)]
print(filtered_df)

    Name Sex  Age  Height  Weigth
1   Bert   M   42      68     166
4   Elly   F   30      66     124
5   Fran   F   33      66     115
6   Gwen   F   26      64     121
9   Jake   M   32      69     143
10  Kate   F   47      69     139
12  Myra   F   23      62      98
15  Page   F   31      67     135
17  Ruth   F   28      65     131

In [20]:
grouped_data = df2.groupby('Sex')
print(grouped_data)
grouped_data.count()

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x00000202BB556BA0>

     Name  Age  Height  Weigth
Sex
F       7    7       7       7
M      11   11      11      11